FROM python:3.11-slim
WORKDIR /app

RUN pip install --no-cache-dir numpy pandas scikit-learn paho-mqtt langchain langchain-community langchain-ollama
COPY agentic_mas_demo.py .

CMD ["python", "agentic_mas_demo.py"]
